# Generated by Django 3.2 on 2022-03-17 18:12

from enums.undangan_type import UndanganType
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Undangan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(UndanganType['O'], 'one'), (UndanganType['G'], 'group')], max_length=3)),
                ('person_type', models.CharField(blank=True, max_length=50, null=True)),
                ('person_name', models.CharField(max_length=100)),
                ('person_partner', models.CharField(blank=True, max_length=50, null=True)),
                ('person_location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_send', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'undangan',
                'managed': True,
            },
        ),
    ]
