# Generated by Django 3.2 on 2022-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucapan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucapan',
            name='sender',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ucapan',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
