# Generated by Django 3.2 on 2022-03-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucapan', '0002_auto_20220319_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucapan',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
