# Generated by Django 3.2 on 2022-03-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticateduser',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
